// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hx2dome.proto

#include "hx2dome.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace hx2dome {
class ReturnCodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReturnCode> _instance;
} _ReturnCode_default_instance_;
class AzElDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AzEl> _instance;
} _AzEl_default_instance_;
class IsCompleteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<IsComplete> _instance;
} _IsComplete_default_instance_;
class BasicStringDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BasicString> _instance;
} _BasicString_default_instance_;
}  // namespace hx2dome
static void InitDefaultsReturnCode_hx2dome_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hx2dome::_ReturnCode_default_instance_;
    new (ptr) ::hx2dome::ReturnCode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hx2dome::ReturnCode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReturnCode_hx2dome_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReturnCode_hx2dome_2eproto}, {}};

static void InitDefaultsAzEl_hx2dome_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hx2dome::_AzEl_default_instance_;
    new (ptr) ::hx2dome::AzEl();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hx2dome::AzEl::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AzEl_hx2dome_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAzEl_hx2dome_2eproto}, {}};

static void InitDefaultsIsComplete_hx2dome_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hx2dome::_IsComplete_default_instance_;
    new (ptr) ::hx2dome::IsComplete();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hx2dome::IsComplete::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_IsComplete_hx2dome_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsIsComplete_hx2dome_2eproto}, {}};

static void InitDefaultsBasicString_hx2dome_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::hx2dome::_BasicString_default_instance_;
    new (ptr) ::hx2dome::BasicString();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hx2dome::BasicString::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BasicString_hx2dome_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBasicString_hx2dome_2eproto}, {}};

void InitDefaults_hx2dome_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReturnCode_hx2dome_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AzEl_hx2dome_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_IsComplete_hx2dome_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BasicString_hx2dome_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_hx2dome_2eproto[4];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_hx2dome_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_hx2dome_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_hx2dome_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::ReturnCode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hx2dome::ReturnCode, return_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, return_code_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, az_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, el_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, return_code_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, is_complete_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::BasicString, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::hx2dome::BasicString, basic_string_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::hx2dome::ReturnCode)},
  { 6, -1, sizeof(::hx2dome::AzEl)},
  { 14, -1, sizeof(::hx2dome::IsComplete)},
  { 21, -1, sizeof(::hx2dome::BasicString)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::hx2dome::_ReturnCode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hx2dome::_AzEl_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hx2dome::_IsComplete_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::hx2dome::_BasicString_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_hx2dome_2eproto = {
  {}, AddDescriptors_hx2dome_2eproto, "hx2dome.proto", schemas,
  file_default_instances, TableStruct_hx2dome_2eproto::offsets,
  file_level_metadata_hx2dome_2eproto, 4, file_level_enum_descriptors_hx2dome_2eproto, file_level_service_descriptors_hx2dome_2eproto,
};

const char descriptor_table_protodef_hx2dome_2eproto[] =
  "\n\rhx2dome.proto\022\007hx2dome\032\033google/protobu"
  "f/empty.proto\"!\n\nReturnCode\022\023\n\013return_co"
  "de\030\001 \001(\005\"3\n\004AzEl\022\023\n\013return_code\030\001 \001(\005\022\n\n"
  "\002az\030\002 \001(\001\022\n\n\002el\030\003 \001(\001\"6\n\nIsComplete\022\023\n\013r"
  "eturn_code\030\001 \001(\005\022\023\n\013is_complete\030\002 \001(\010\"#\n"
  "\013BasicString\022\024\n\014basic_string\030\001 \001(\t2\232\n\n\007H"
  "X2Dome\0226\n\013dapiGetAzEl\022\026.google.protobuf."
  "Empty\032\r.hx2dome.AzEl\"\000\0224\n\014dapiGotoAzEl\022\r"
  ".hx2dome.AzEl\032\023.hx2dome.ReturnCode\"\000\022:\n\t"
  "dapiAbort\022\026.google.protobuf.Empty\032\023.hx2d"
  "ome.ReturnCode\"\000\0229\n\010dapiOpen\022\026.google.pr"
  "otobuf.Empty\032\023.hx2dome.ReturnCode\"\000\022:\n\td"
  "apiClose\022\026.google.protobuf.Empty\032\023.hx2do"
  "me.ReturnCode\"\000\0229\n\010dapiPark\022\026.google.pro"
  "tobuf.Empty\032\023.hx2dome.ReturnCode\"\000\022;\n\nda"
  "piUnpark\022\026.google.protobuf.Empty\032\023.hx2do"
  "me.ReturnCode\"\000\022=\n\014dapiFindHome\022\026.google"
  ".protobuf.Empty\032\023.hx2dome.ReturnCode\"\000\022A"
  "\n\020dapiGotoComplete\022\026.google.protobuf.Emp"
  "ty\032\023.hx2dome.IsComplete\"\000\022A\n\020dapiOpenCom"
  "plete\022\026.google.protobuf.Empty\032\023.hx2dome."
  "IsComplete\"\000\022B\n\021dapiCloseComplete\022\026.goog"
  "le.protobuf.Empty\032\023.hx2dome.IsComplete\"\000"
  "\022A\n\020dapiParkComplete\022\026.google.protobuf.E"
  "mpty\032\023.hx2dome.IsComplete\"\000\022C\n\022dapiUnpar"
  "kComplete\022\026.google.protobuf.Empty\032\023.hx2d"
  "ome.IsComplete\"\000\022E\n\024dapiFindHomeComplete"
  "\022\026.google.protobuf.Empty\032\023.hx2dome.IsCom"
  "plete\"\000\0220\n\010dapiSync\022\r.hx2dome.AzEl\032\023.hx2"
  "dome.ReturnCode\"\000\022E\n\023deviceInfoNameShort"
  "\022\026.google.protobuf.Empty\032\024.hx2dome.Basic"
  "String\"\000\022D\n\022deviceInfoNameLong\022\026.google."
  "protobuf.Empty\032\024.hx2dome.BasicString\"\000\022O"
  "\n\035deviceInfoDetailedDescription\022\026.google"
  ".protobuf.Empty\032\024.hx2dome.BasicString\"\000\022"
  "K\n\031deviceInfoFirmwareVersion\022\026.google.pr"
  "otobuf.Empty\032\024.hx2dome.BasicString\"\000\022A\n\017"
  "deviceInfoModel\022\026.google.protobuf.Empty\032"
  "\024.hx2dome.BasicString\"\000b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_hx2dome_2eproto = {
  false, InitDefaults_hx2dome_2eproto, 
  descriptor_table_protodef_hx2dome_2eproto,
  "hx2dome.proto", &assign_descriptors_table_hx2dome_2eproto, 1551,
};

void AddDescriptors_hx2dome_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fempty_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_hx2dome_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_hx2dome_2eproto = []() { AddDescriptors_hx2dome_2eproto(); return true; }();
namespace hx2dome {

// ===================================================================

void ReturnCode::InitAsDefaultInstance() {
}
class ReturnCode::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReturnCode::kReturnCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReturnCode::ReturnCode()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hx2dome.ReturnCode)
}
ReturnCode::ReturnCode(const ReturnCode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  return_code_ = from.return_code_;
  // @@protoc_insertion_point(copy_constructor:hx2dome.ReturnCode)
}

void ReturnCode::SharedCtor() {
  return_code_ = 0;
}

ReturnCode::~ReturnCode() {
  // @@protoc_insertion_point(destructor:hx2dome.ReturnCode)
  SharedDtor();
}

void ReturnCode::SharedDtor() {
}

void ReturnCode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ReturnCode& ReturnCode::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ReturnCode_hx2dome_2eproto.base);
  return *internal_default_instance();
}


void ReturnCode::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.ReturnCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return_code_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ReturnCode::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ReturnCode*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_return_code(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ReturnCode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hx2dome.ReturnCode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &return_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hx2dome.ReturnCode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hx2dome.ReturnCode)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ReturnCode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hx2dome.ReturnCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->return_code(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hx2dome.ReturnCode)
}

::google::protobuf::uint8* ReturnCode::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.ReturnCode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->return_code(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.ReturnCode)
  return target;
}

size_t ReturnCode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.ReturnCode)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->return_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReturnCode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hx2dome.ReturnCode)
  GOOGLE_DCHECK_NE(&from, this);
  const ReturnCode* source =
      ::google::protobuf::DynamicCastToGenerated<ReturnCode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hx2dome.ReturnCode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hx2dome.ReturnCode)
    MergeFrom(*source);
  }
}

void ReturnCode::MergeFrom(const ReturnCode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.ReturnCode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.return_code() != 0) {
    set_return_code(from.return_code());
  }
}

void ReturnCode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hx2dome.ReturnCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReturnCode::CopyFrom(const ReturnCode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.ReturnCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReturnCode::IsInitialized() const {
  return true;
}

void ReturnCode::Swap(ReturnCode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReturnCode::InternalSwap(ReturnCode* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(return_code_, other->return_code_);
}

::google::protobuf::Metadata ReturnCode::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_hx2dome_2eproto);
  return ::file_level_metadata_hx2dome_2eproto[kIndexInFileMessages];
}


// ===================================================================

void AzEl::InitAsDefaultInstance() {
}
class AzEl::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AzEl::kReturnCodeFieldNumber;
const int AzEl::kAzFieldNumber;
const int AzEl::kElFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AzEl::AzEl()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hx2dome.AzEl)
}
AzEl::AzEl(const AzEl& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&az_, &from.az_,
    static_cast<size_t>(reinterpret_cast<char*>(&return_code_) -
    reinterpret_cast<char*>(&az_)) + sizeof(return_code_));
  // @@protoc_insertion_point(copy_constructor:hx2dome.AzEl)
}

void AzEl::SharedCtor() {
  ::memset(&az_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&return_code_) -
      reinterpret_cast<char*>(&az_)) + sizeof(return_code_));
}

AzEl::~AzEl() {
  // @@protoc_insertion_point(destructor:hx2dome.AzEl)
  SharedDtor();
}

void AzEl::SharedDtor() {
}

void AzEl::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AzEl& AzEl::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_AzEl_hx2dome_2eproto.base);
  return *internal_default_instance();
}


void AzEl::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.AzEl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&az_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&return_code_) -
      reinterpret_cast<char*>(&az_)) + sizeof(return_code_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* AzEl::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<AzEl*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_return_code(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // double az = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 17) goto handle_unusual;
        msg->set_az(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // double el = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 25) goto handle_unusual;
        msg->set_el(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool AzEl::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hx2dome.AzEl)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &return_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double az = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (17 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &az_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double el = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (25 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &el_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hx2dome.AzEl)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hx2dome.AzEl)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void AzEl::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hx2dome.AzEl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->return_code(), output);
  }

  // double az = 2;
  if (this->az() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->az(), output);
  }

  // double el = 3;
  if (this->el() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->el(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hx2dome.AzEl)
}

::google::protobuf::uint8* AzEl::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.AzEl)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->return_code(), target);
  }

  // double az = 2;
  if (this->az() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->az(), target);
  }

  // double el = 3;
  if (this->el() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->el(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.AzEl)
  return target;
}

size_t AzEl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.AzEl)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double az = 2;
  if (this->az() != 0) {
    total_size += 1 + 8;
  }

  // double el = 3;
  if (this->el() != 0) {
    total_size += 1 + 8;
  }

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->return_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AzEl::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hx2dome.AzEl)
  GOOGLE_DCHECK_NE(&from, this);
  const AzEl* source =
      ::google::protobuf::DynamicCastToGenerated<AzEl>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hx2dome.AzEl)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hx2dome.AzEl)
    MergeFrom(*source);
  }
}

void AzEl::MergeFrom(const AzEl& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.AzEl)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.az() != 0) {
    set_az(from.az());
  }
  if (from.el() != 0) {
    set_el(from.el());
  }
  if (from.return_code() != 0) {
    set_return_code(from.return_code());
  }
}

void AzEl::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hx2dome.AzEl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AzEl::CopyFrom(const AzEl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.AzEl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AzEl::IsInitialized() const {
  return true;
}

void AzEl::Swap(AzEl* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AzEl::InternalSwap(AzEl* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(az_, other->az_);
  swap(el_, other->el_);
  swap(return_code_, other->return_code_);
}

::google::protobuf::Metadata AzEl::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_hx2dome_2eproto);
  return ::file_level_metadata_hx2dome_2eproto[kIndexInFileMessages];
}


// ===================================================================

void IsComplete::InitAsDefaultInstance() {
}
class IsComplete::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int IsComplete::kReturnCodeFieldNumber;
const int IsComplete::kIsCompleteFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

IsComplete::IsComplete()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hx2dome.IsComplete)
}
IsComplete::IsComplete(const IsComplete& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&return_code_, &from.return_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_complete_) -
    reinterpret_cast<char*>(&return_code_)) + sizeof(is_complete_));
  // @@protoc_insertion_point(copy_constructor:hx2dome.IsComplete)
}

void IsComplete::SharedCtor() {
  ::memset(&return_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_complete_) -
      reinterpret_cast<char*>(&return_code_)) + sizeof(is_complete_));
}

IsComplete::~IsComplete() {
  // @@protoc_insertion_point(destructor:hx2dome.IsComplete)
  SharedDtor();
}

void IsComplete::SharedDtor() {
}

void IsComplete::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IsComplete& IsComplete::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_IsComplete_hx2dome_2eproto.base);
  return *internal_default_instance();
}


void IsComplete::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.IsComplete)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&return_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_complete_) -
      reinterpret_cast<char*>(&return_code_)) + sizeof(is_complete_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* IsComplete::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<IsComplete*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_return_code(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bool is_complete = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_is_complete(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool IsComplete::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hx2dome.IsComplete)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 return_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &return_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_complete = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_complete_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hx2dome.IsComplete)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hx2dome.IsComplete)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void IsComplete::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hx2dome.IsComplete)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->return_code(), output);
  }

  // bool is_complete = 2;
  if (this->is_complete() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->is_complete(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hx2dome.IsComplete)
}

::google::protobuf::uint8* IsComplete::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.IsComplete)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->return_code(), target);
  }

  // bool is_complete = 2;
  if (this->is_complete() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->is_complete(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.IsComplete)
  return target;
}

size_t IsComplete::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.IsComplete)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->return_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->return_code());
  }

  // bool is_complete = 2;
  if (this->is_complete() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IsComplete::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hx2dome.IsComplete)
  GOOGLE_DCHECK_NE(&from, this);
  const IsComplete* source =
      ::google::protobuf::DynamicCastToGenerated<IsComplete>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hx2dome.IsComplete)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hx2dome.IsComplete)
    MergeFrom(*source);
  }
}

void IsComplete::MergeFrom(const IsComplete& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.IsComplete)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.return_code() != 0) {
    set_return_code(from.return_code());
  }
  if (from.is_complete() != 0) {
    set_is_complete(from.is_complete());
  }
}

void IsComplete::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hx2dome.IsComplete)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IsComplete::CopyFrom(const IsComplete& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.IsComplete)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IsComplete::IsInitialized() const {
  return true;
}

void IsComplete::Swap(IsComplete* other) {
  if (other == this) return;
  InternalSwap(other);
}
void IsComplete::InternalSwap(IsComplete* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(return_code_, other->return_code_);
  swap(is_complete_, other->is_complete_);
}

::google::protobuf::Metadata IsComplete::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_hx2dome_2eproto);
  return ::file_level_metadata_hx2dome_2eproto[kIndexInFileMessages];
}


// ===================================================================

void BasicString::InitAsDefaultInstance() {
}
class BasicString::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BasicString::kBasicStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BasicString::BasicString()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hx2dome.BasicString)
}
BasicString::BasicString(const BasicString& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  basic_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.basic_string().size() > 0) {
    basic_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.basic_string_);
  }
  // @@protoc_insertion_point(copy_constructor:hx2dome.BasicString)
}

void BasicString::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_BasicString_hx2dome_2eproto.base);
  basic_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BasicString::~BasicString() {
  // @@protoc_insertion_point(destructor:hx2dome.BasicString)
  SharedDtor();
}

void BasicString::SharedDtor() {
  basic_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BasicString::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BasicString& BasicString::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_BasicString_hx2dome_2eproto.base);
  return *internal_default_instance();
}


void BasicString::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.BasicString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  basic_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* BasicString::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<BasicString*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string basic_string = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("hx2dome.BasicString.basic_string");
        object = msg->mutable_basic_string();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool BasicString::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hx2dome.BasicString)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string basic_string = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_basic_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->basic_string().data(), static_cast<int>(this->basic_string().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "hx2dome.BasicString.basic_string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hx2dome.BasicString)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hx2dome.BasicString)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void BasicString::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hx2dome.BasicString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string basic_string = 1;
  if (this->basic_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->basic_string().data(), static_cast<int>(this->basic_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hx2dome.BasicString.basic_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->basic_string(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hx2dome.BasicString)
}

::google::protobuf::uint8* BasicString::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.BasicString)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string basic_string = 1;
  if (this->basic_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->basic_string().data(), static_cast<int>(this->basic_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hx2dome.BasicString.basic_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->basic_string(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.BasicString)
  return target;
}

size_t BasicString::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.BasicString)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string basic_string = 1;
  if (this->basic_string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->basic_string());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BasicString::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hx2dome.BasicString)
  GOOGLE_DCHECK_NE(&from, this);
  const BasicString* source =
      ::google::protobuf::DynamicCastToGenerated<BasicString>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hx2dome.BasicString)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hx2dome.BasicString)
    MergeFrom(*source);
  }
}

void BasicString::MergeFrom(const BasicString& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.BasicString)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.basic_string().size() > 0) {

    basic_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.basic_string_);
  }
}

void BasicString::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hx2dome.BasicString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BasicString::CopyFrom(const BasicString& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.BasicString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicString::IsInitialized() const {
  return true;
}

void BasicString::Swap(BasicString* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BasicString::InternalSwap(BasicString* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  basic_string_.Swap(&other->basic_string_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata BasicString::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_hx2dome_2eproto);
  return ::file_level_metadata_hx2dome_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace hx2dome
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::hx2dome::ReturnCode* Arena::CreateMaybeMessage< ::hx2dome::ReturnCode >(Arena* arena) {
  return Arena::CreateInternal< ::hx2dome::ReturnCode >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::AzEl* Arena::CreateMaybeMessage< ::hx2dome::AzEl >(Arena* arena) {
  return Arena::CreateInternal< ::hx2dome::AzEl >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::IsComplete* Arena::CreateMaybeMessage< ::hx2dome::IsComplete >(Arena* arena) {
  return Arena::CreateInternal< ::hx2dome::IsComplete >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::BasicString* Arena::CreateMaybeMessage< ::hx2dome::BasicString >(Arena* arena) {
  return Arena::CreateInternal< ::hx2dome::BasicString >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
