// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hx2dome.proto

#ifndef PROTOBUF_INCLUDED_hx2dome_2eproto
#define PROTOBUF_INCLUDED_hx2dome_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hx2dome_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_hx2dome_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_hx2dome_2eproto();
namespace hx2dome {
class AzEl;
class AzElDefaultTypeInternal;
extern AzElDefaultTypeInternal _AzEl_default_instance_;
class BasicString;
class BasicStringDefaultTypeInternal;
extern BasicStringDefaultTypeInternal _BasicString_default_instance_;
class IsComplete;
class IsCompleteDefaultTypeInternal;
extern IsCompleteDefaultTypeInternal _IsComplete_default_instance_;
class ReturnCode;
class ReturnCodeDefaultTypeInternal;
extern ReturnCodeDefaultTypeInternal _ReturnCode_default_instance_;
}  // namespace hx2dome
namespace google {
namespace protobuf {
template<> ::hx2dome::AzEl* Arena::CreateMaybeMessage<::hx2dome::AzEl>(Arena*);
template<> ::hx2dome::BasicString* Arena::CreateMaybeMessage<::hx2dome::BasicString>(Arena*);
template<> ::hx2dome::IsComplete* Arena::CreateMaybeMessage<::hx2dome::IsComplete>(Arena*);
template<> ::hx2dome::ReturnCode* Arena::CreateMaybeMessage<::hx2dome::ReturnCode>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace hx2dome {

// ===================================================================

class ReturnCode final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hx2dome.ReturnCode) */ {
 public:
  ReturnCode();
  virtual ~ReturnCode();

  ReturnCode(const ReturnCode& from);

  inline ReturnCode& operator=(const ReturnCode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReturnCode(ReturnCode&& from) noexcept
    : ReturnCode() {
    *this = ::std::move(from);
  }

  inline ReturnCode& operator=(ReturnCode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ReturnCode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReturnCode* internal_default_instance() {
    return reinterpret_cast<const ReturnCode*>(
               &_ReturnCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReturnCode* other);
  friend void swap(ReturnCode& a, ReturnCode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReturnCode* New() const final {
    return CreateMaybeMessage<ReturnCode>(nullptr);
  }

  ReturnCode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReturnCode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReturnCode& from);
  void MergeFrom(const ReturnCode& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReturnCode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 return_code = 1;
  void clear_return_code();
  static const int kReturnCodeFieldNumber = 1;
  ::google::protobuf::int32 return_code() const;
  void set_return_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hx2dome.ReturnCode)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 return_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class AzEl final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hx2dome.AzEl) */ {
 public:
  AzEl();
  virtual ~AzEl();

  AzEl(const AzEl& from);

  inline AzEl& operator=(const AzEl& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AzEl(AzEl&& from) noexcept
    : AzEl() {
    *this = ::std::move(from);
  }

  inline AzEl& operator=(AzEl&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AzEl& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AzEl* internal_default_instance() {
    return reinterpret_cast<const AzEl*>(
               &_AzEl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AzEl* other);
  friend void swap(AzEl& a, AzEl& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AzEl* New() const final {
    return CreateMaybeMessage<AzEl>(nullptr);
  }

  AzEl* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AzEl>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AzEl& from);
  void MergeFrom(const AzEl& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AzEl* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double az = 2;
  void clear_az();
  static const int kAzFieldNumber = 2;
  double az() const;
  void set_az(double value);

  // double el = 3;
  void clear_el();
  static const int kElFieldNumber = 3;
  double el() const;
  void set_el(double value);

  // int32 return_code = 1;
  void clear_return_code();
  static const int kReturnCodeFieldNumber = 1;
  ::google::protobuf::int32 return_code() const;
  void set_return_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hx2dome.AzEl)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double az_;
  double el_;
  ::google::protobuf::int32 return_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class IsComplete final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hx2dome.IsComplete) */ {
 public:
  IsComplete();
  virtual ~IsComplete();

  IsComplete(const IsComplete& from);

  inline IsComplete& operator=(const IsComplete& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  IsComplete(IsComplete&& from) noexcept
    : IsComplete() {
    *this = ::std::move(from);
  }

  inline IsComplete& operator=(IsComplete&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const IsComplete& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IsComplete* internal_default_instance() {
    return reinterpret_cast<const IsComplete*>(
               &_IsComplete_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(IsComplete* other);
  friend void swap(IsComplete& a, IsComplete& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline IsComplete* New() const final {
    return CreateMaybeMessage<IsComplete>(nullptr);
  }

  IsComplete* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<IsComplete>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const IsComplete& from);
  void MergeFrom(const IsComplete& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IsComplete* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 return_code = 1;
  void clear_return_code();
  static const int kReturnCodeFieldNumber = 1;
  ::google::protobuf::int32 return_code() const;
  void set_return_code(::google::protobuf::int32 value);

  // bool is_complete = 2;
  void clear_is_complete();
  static const int kIsCompleteFieldNumber = 2;
  bool is_complete() const;
  void set_is_complete(bool value);

  // @@protoc_insertion_point(class_scope:hx2dome.IsComplete)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 return_code_;
  bool is_complete_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class BasicString final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hx2dome.BasicString) */ {
 public:
  BasicString();
  virtual ~BasicString();

  BasicString(const BasicString& from);

  inline BasicString& operator=(const BasicString& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BasicString(BasicString&& from) noexcept
    : BasicString() {
    *this = ::std::move(from);
  }

  inline BasicString& operator=(BasicString&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BasicString& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BasicString* internal_default_instance() {
    return reinterpret_cast<const BasicString*>(
               &_BasicString_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(BasicString* other);
  friend void swap(BasicString& a, BasicString& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BasicString* New() const final {
    return CreateMaybeMessage<BasicString>(nullptr);
  }

  BasicString* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BasicString>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BasicString& from);
  void MergeFrom(const BasicString& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicString* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string basic_string = 1;
  void clear_basic_string();
  static const int kBasicStringFieldNumber = 1;
  const ::std::string& basic_string() const;
  void set_basic_string(const ::std::string& value);
  #if LANG_CXX11
  void set_basic_string(::std::string&& value);
  #endif
  void set_basic_string(const char* value);
  void set_basic_string(const char* value, size_t size);
  ::std::string* mutable_basic_string();
  ::std::string* release_basic_string();
  void set_allocated_basic_string(::std::string* basic_string);

  // @@protoc_insertion_point(class_scope:hx2dome.BasicString)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr basic_string_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hx2dome_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReturnCode

// int32 return_code = 1;
inline void ReturnCode::clear_return_code() {
  return_code_ = 0;
}
inline ::google::protobuf::int32 ReturnCode::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.ReturnCode.return_code)
  return return_code_;
}
inline void ReturnCode::set_return_code(::google::protobuf::int32 value) {
  
  return_code_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.ReturnCode.return_code)
}

// -------------------------------------------------------------------

// AzEl

// int32 return_code = 1;
inline void AzEl::clear_return_code() {
  return_code_ = 0;
}
inline ::google::protobuf::int32 AzEl::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.return_code)
  return return_code_;
}
inline void AzEl::set_return_code(::google::protobuf::int32 value) {
  
  return_code_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.return_code)
}

// double az = 2;
inline void AzEl::clear_az() {
  az_ = 0;
}
inline double AzEl::az() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.az)
  return az_;
}
inline void AzEl::set_az(double value) {
  
  az_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.az)
}

// double el = 3;
inline void AzEl::clear_el() {
  el_ = 0;
}
inline double AzEl::el() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.el)
  return el_;
}
inline void AzEl::set_el(double value) {
  
  el_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.el)
}

// -------------------------------------------------------------------

// IsComplete

// int32 return_code = 1;
inline void IsComplete::clear_return_code() {
  return_code_ = 0;
}
inline ::google::protobuf::int32 IsComplete::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.IsComplete.return_code)
  return return_code_;
}
inline void IsComplete::set_return_code(::google::protobuf::int32 value) {
  
  return_code_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.IsComplete.return_code)
}

// bool is_complete = 2;
inline void IsComplete::clear_is_complete() {
  is_complete_ = false;
}
inline bool IsComplete::is_complete() const {
  // @@protoc_insertion_point(field_get:hx2dome.IsComplete.is_complete)
  return is_complete_;
}
inline void IsComplete::set_is_complete(bool value) {
  
  is_complete_ = value;
  // @@protoc_insertion_point(field_set:hx2dome.IsComplete.is_complete)
}

// -------------------------------------------------------------------

// BasicString

// string basic_string = 1;
inline void BasicString::clear_basic_string() {
  basic_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BasicString::basic_string() const {
  // @@protoc_insertion_point(field_get:hx2dome.BasicString.basic_string)
  return basic_string_.GetNoArena();
}
inline void BasicString::set_basic_string(const ::std::string& value) {
  
  basic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hx2dome.BasicString.basic_string)
}
#if LANG_CXX11
inline void BasicString::set_basic_string(::std::string&& value) {
  
  basic_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hx2dome.BasicString.basic_string)
}
#endif
inline void BasicString::set_basic_string(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  basic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hx2dome.BasicString.basic_string)
}
inline void BasicString::set_basic_string(const char* value, size_t size) {
  
  basic_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hx2dome.BasicString.basic_string)
}
inline ::std::string* BasicString::mutable_basic_string() {
  
  // @@protoc_insertion_point(field_mutable:hx2dome.BasicString.basic_string)
  return basic_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BasicString::release_basic_string() {
  // @@protoc_insertion_point(field_release:hx2dome.BasicString.basic_string)
  
  return basic_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BasicString::set_allocated_basic_string(::std::string* basic_string) {
  if (basic_string != nullptr) {
    
  } else {
    
  }
  basic_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), basic_string);
  // @@protoc_insertion_point(field_set_allocated:hx2dome.BasicString.basic_string)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hx2dome

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_hx2dome_2eproto
