// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hx2dome.proto

#include "hx2dome.pb.h"
#include "hx2dome.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hx2dome {

static const char* HX2Dome_method_names[] = {
  "/hx2dome.HX2Dome/dapiGetAzEl",
  "/hx2dome.HX2Dome/dapiGotoAzEl",
  "/hx2dome.HX2Dome/dapiAbort",
  "/hx2dome.HX2Dome/dapiOpen",
  "/hx2dome.HX2Dome/dapiClose",
  "/hx2dome.HX2Dome/dapiPark",
  "/hx2dome.HX2Dome/dapiUnpark",
  "/hx2dome.HX2Dome/dapiFindHome",
  "/hx2dome.HX2Dome/dapiIsGotoComplete",
  "/hx2dome.HX2Dome/dapiIsOpenComplete",
  "/hx2dome.HX2Dome/dapiIsCloseComplete",
  "/hx2dome.HX2Dome/dapiIsParkComplete",
  "/hx2dome.HX2Dome/dapiIsUnparkComplete",
  "/hx2dome.HX2Dome/dapiIsFindHomeComplete",
  "/hx2dome.HX2Dome/dapiSync",
  "/hx2dome.HX2Dome/deviceInfoNameShort",
  "/hx2dome.HX2Dome/deviceInfoNameLong",
  "/hx2dome.HX2Dome/deviceInfoDetailedDescription",
  "/hx2dome.HX2Dome/deviceInfoFirmwareVersion",
  "/hx2dome.HX2Dome/deviceInfoModel",
};

std::unique_ptr< HX2Dome::Stub> HX2Dome::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HX2Dome::Stub> stub(new HX2Dome::Stub(channel, options));
  return stub;
}

HX2Dome::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_dapiGetAzEl_(HX2Dome_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiGotoAzEl_(HX2Dome_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiAbort_(HX2Dome_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiOpen_(HX2Dome_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiClose_(HX2Dome_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiPark_(HX2Dome_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiUnpark_(HX2Dome_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiFindHome_(HX2Dome_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsGotoComplete_(HX2Dome_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsOpenComplete_(HX2Dome_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsCloseComplete_(HX2Dome_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsParkComplete_(HX2Dome_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsUnparkComplete_(HX2Dome_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiIsFindHomeComplete_(HX2Dome_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_dapiSync_(HX2Dome_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deviceInfoNameShort_(HX2Dome_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deviceInfoNameLong_(HX2Dome_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deviceInfoDetailedDescription_(HX2Dome_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deviceInfoFirmwareVersion_(HX2Dome_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_deviceInfoModel_(HX2Dome_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HX2Dome::Stub::dapiGetAzEl(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::AzEl* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::AzEl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiGetAzEl_, context, request, response);
}

void HX2Dome::Stub::async::dapiGetAzEl(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::AzEl* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::AzEl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiGetAzEl_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiGetAzEl(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::AzEl* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiGetAzEl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::AzEl>* HX2Dome::Stub::PrepareAsyncdapiGetAzElRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::AzEl, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiGetAzEl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::AzEl>* HX2Dome::Stub::AsyncdapiGetAzElRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiGetAzElRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiGotoAzEl(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiGotoAzEl_, context, request, response);
}

void HX2Dome::Stub::async::dapiGotoAzEl(::grpc::ClientContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiGotoAzEl_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiGotoAzEl(::grpc::ClientContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiGotoAzEl_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiGotoAzElRaw(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::AzEl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiGotoAzEl_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiGotoAzElRaw(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiGotoAzElRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiAbort(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiAbort_, context, request, response);
}

void HX2Dome::Stub::async::dapiAbort(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiAbort_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiAbort(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiAbort_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiAbortRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiAbort_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiAbortRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiAbortRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiOpen(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiOpen_, context, request, response);
}

void HX2Dome::Stub::async::dapiOpen(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiOpen_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiOpen(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiOpen_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiOpenRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiOpen_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiOpenRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiOpenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiClose(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiClose_, context, request, response);
}

void HX2Dome::Stub::async::dapiClose(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiClose_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiClose(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiClose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiCloseRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiClose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiCloseRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiCloseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiPark(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiPark_, context, request, response);
}

void HX2Dome::Stub::async::dapiPark(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiPark_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiPark(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiPark_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiParkRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiPark_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiParkRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiParkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiUnpark(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiUnpark_, context, request, response);
}

void HX2Dome::Stub::async::dapiUnpark(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiUnpark_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiUnpark(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiUnpark_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiUnparkRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiUnpark_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiUnparkRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiUnparkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiFindHome(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiFindHome_, context, request, response);
}

void HX2Dome::Stub::async::dapiFindHome(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiFindHome_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiFindHome(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiFindHome_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiFindHomeRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiFindHome_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiFindHomeRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiFindHomeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsGotoComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsGotoComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsGotoComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsGotoComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsGotoComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsGotoComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsGotoCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsGotoComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsGotoCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsGotoCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsOpenComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsOpenComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsOpenComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsOpenComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsOpenComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsOpenComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsOpenCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsOpenComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsOpenCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsOpenCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsCloseComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsCloseComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsCloseComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsCloseComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsCloseComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsCloseComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsCloseCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsCloseComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsCloseCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsCloseCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsParkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsParkComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsParkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsParkComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsParkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsParkComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsParkCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsParkComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsParkCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsParkCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsUnparkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsUnparkComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsUnparkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsUnparkComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsUnparkComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsUnparkComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsUnparkCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsUnparkComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsUnparkCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsUnparkCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiIsFindHomeComplete(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::IsComplete* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiIsFindHomeComplete_, context, request, response);
}

void HX2Dome::Stub::async::dapiIsFindHomeComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsFindHomeComplete_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiIsFindHomeComplete(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiIsFindHomeComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::PrepareAsyncdapiIsFindHomeCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::IsComplete, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiIsFindHomeComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::IsComplete>* HX2Dome::Stub::AsyncdapiIsFindHomeCompleteRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiIsFindHomeCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::dapiSync(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::hx2dome::ReturnCode* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_dapiSync_, context, request, response);
}

void HX2Dome::Stub::async::dapiSync(::grpc::ClientContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiSync_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::dapiSync(::grpc::ClientContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_dapiSync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::PrepareAsyncdapiSyncRaw(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::ReturnCode, ::hx2dome::AzEl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_dapiSync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::ReturnCode>* HX2Dome::Stub::AsyncdapiSyncRaw(::grpc::ClientContext* context, const ::hx2dome::AzEl& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdapiSyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::deviceInfoNameShort(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::BasicString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_deviceInfoNameShort_, context, request, response);
}

void HX2Dome::Stub::async::deviceInfoNameShort(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoNameShort_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::deviceInfoNameShort(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoNameShort_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::PrepareAsyncdeviceInfoNameShortRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::BasicString, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_deviceInfoNameShort_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::AsyncdeviceInfoNameShortRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdeviceInfoNameShortRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::deviceInfoNameLong(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::BasicString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_deviceInfoNameLong_, context, request, response);
}

void HX2Dome::Stub::async::deviceInfoNameLong(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoNameLong_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::deviceInfoNameLong(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoNameLong_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::PrepareAsyncdeviceInfoNameLongRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::BasicString, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_deviceInfoNameLong_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::AsyncdeviceInfoNameLongRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdeviceInfoNameLongRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::deviceInfoDetailedDescription(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::BasicString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_deviceInfoDetailedDescription_, context, request, response);
}

void HX2Dome::Stub::async::deviceInfoDetailedDescription(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoDetailedDescription_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::deviceInfoDetailedDescription(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoDetailedDescription_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::PrepareAsyncdeviceInfoDetailedDescriptionRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::BasicString, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_deviceInfoDetailedDescription_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::AsyncdeviceInfoDetailedDescriptionRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdeviceInfoDetailedDescriptionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::deviceInfoFirmwareVersion(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::BasicString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_deviceInfoFirmwareVersion_, context, request, response);
}

void HX2Dome::Stub::async::deviceInfoFirmwareVersion(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoFirmwareVersion_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::deviceInfoFirmwareVersion(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoFirmwareVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::PrepareAsyncdeviceInfoFirmwareVersionRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::BasicString, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_deviceInfoFirmwareVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::AsyncdeviceInfoFirmwareVersionRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdeviceInfoFirmwareVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HX2Dome::Stub::deviceInfoModel(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::hx2dome::BasicString* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_deviceInfoModel_, context, request, response);
}

void HX2Dome::Stub::async::deviceInfoModel(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoModel_, context, request, response, std::move(f));
}

void HX2Dome::Stub::async::deviceInfoModel(::grpc::ClientContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_deviceInfoModel_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::PrepareAsyncdeviceInfoModelRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hx2dome::BasicString, ::hx2dome::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_deviceInfoModel_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hx2dome::BasicString>* HX2Dome::Stub::AsyncdeviceInfoModelRaw(::grpc::ClientContext* context, const ::hx2dome::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncdeviceInfoModelRaw(context, request, cq);
  result->StartCall();
  return result;
}

HX2Dome::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::AzEl, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::AzEl* resp) {
               return service->dapiGetAzEl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::AzEl* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiGotoAzEl(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiAbort(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiOpen(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiClose(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiPark(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiUnpark(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiFindHome(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsGotoComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsOpenComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsCloseComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsParkComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsUnparkComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::IsComplete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::IsComplete* resp) {
               return service->dapiIsFindHomeComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::AzEl, ::hx2dome::ReturnCode, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::AzEl* req,
             ::hx2dome::ReturnCode* resp) {
               return service->dapiSync(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::BasicString* resp) {
               return service->deviceInfoNameShort(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::BasicString* resp) {
               return service->deviceInfoNameLong(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::BasicString* resp) {
               return service->deviceInfoDetailedDescription(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::BasicString* resp) {
               return service->deviceInfoFirmwareVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HX2Dome_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HX2Dome::Service, ::hx2dome::Empty, ::hx2dome::BasicString, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HX2Dome::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hx2dome::Empty* req,
             ::hx2dome::BasicString* resp) {
               return service->deviceInfoModel(ctx, req, resp);
             }, this)));
}

HX2Dome::Service::~Service() {
}

::grpc::Status HX2Dome::Service::dapiGetAzEl(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::AzEl* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiGotoAzEl(::grpc::ServerContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiAbort(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiOpen(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiClose(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiPark(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiUnpark(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiFindHome(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsGotoComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsOpenComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsCloseComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsParkComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsUnparkComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiIsFindHomeComplete(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::IsComplete* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::dapiSync(::grpc::ServerContext* context, const ::hx2dome::AzEl* request, ::hx2dome::ReturnCode* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::deviceInfoNameShort(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::deviceInfoNameLong(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::deviceInfoDetailedDescription(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::deviceInfoFirmwareVersion(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HX2Dome::Service::deviceInfoModel(::grpc::ServerContext* context, const ::hx2dome::Empty* request, ::hx2dome::BasicString* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hx2dome

