// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hx2dome.proto

#include "hx2dome.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace hx2dome {
PROTOBUF_CONSTEXPR ReturnCode::ReturnCode(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.return_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReturnCodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReturnCodeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReturnCodeDefaultTypeInternal() {}
  union {
    ReturnCode _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReturnCodeDefaultTypeInternal _ReturnCode_default_instance_;
PROTOBUF_CONSTEXPR AzEl::AzEl(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.az_)*/0
  , /*decltype(_impl_.el_)*/0
  , /*decltype(_impl_.return_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AzElDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AzElDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AzElDefaultTypeInternal() {}
  union {
    AzEl _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AzElDefaultTypeInternal _AzEl_default_instance_;
PROTOBUF_CONSTEXPR IsComplete::IsComplete(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.return_code_)*/0
  , /*decltype(_impl_.is_complete_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IsCompleteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IsCompleteDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IsCompleteDefaultTypeInternal() {}
  union {
    IsComplete _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IsCompleteDefaultTypeInternal _IsComplete_default_instance_;
PROTOBUF_CONSTEXPR BasicString::BasicString(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.basic_string_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BasicStringDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BasicStringDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BasicStringDefaultTypeInternal() {}
  union {
    BasicString _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BasicStringDefaultTypeInternal _BasicString_default_instance_;
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace hx2dome
static ::_pb::Metadata file_level_metadata_hx2dome_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_hx2dome_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_hx2dome_2eproto = nullptr;

const uint32_t TableStruct_hx2dome_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::ReturnCode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hx2dome::ReturnCode, _impl_.return_code_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::ReturnCode, _impl_.error_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, _impl_.return_code_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, _impl_.az_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::AzEl, _impl_.el_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, _impl_.return_code_),
  PROTOBUF_FIELD_OFFSET(::hx2dome::IsComplete, _impl_.is_complete_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::BasicString, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::hx2dome::BasicString, _impl_.basic_string_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::hx2dome::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::hx2dome::ReturnCode)},
  { 8, -1, -1, sizeof(::hx2dome::AzEl)},
  { 17, -1, -1, sizeof(::hx2dome::IsComplete)},
  { 25, -1, -1, sizeof(::hx2dome::BasicString)},
  { 32, -1, -1, sizeof(::hx2dome::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::hx2dome::_ReturnCode_default_instance_._instance,
  &::hx2dome::_AzEl_default_instance_._instance,
  &::hx2dome::_IsComplete_default_instance_._instance,
  &::hx2dome::_BasicString_default_instance_._instance,
  &::hx2dome::_Empty_default_instance_._instance,
};

const char descriptor_table_protodef_hx2dome_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rhx2dome.proto\022\007hx2dome\"8\n\nReturnCode\022\023"
  "\n\013return_code\030\001 \001(\005\022\025\n\rerror_message\030\002 \001"
  "(\t\"3\n\004AzEl\022\023\n\013return_code\030\001 \001(\005\022\n\n\002az\030\002 "
  "\001(\001\022\n\n\002el\030\003 \001(\001\"6\n\nIsComplete\022\023\n\013return_"
  "code\030\001 \001(\005\022\023\n\013is_complete\030\002 \001(\010\"#\n\013Basic"
  "String\022\024\n\014basic_string\030\001 \001(\t\"\007\n\005Empty2\226\t"
  "\n\007HX2Dome\022.\n\013dapiGetAzEl\022\016.hx2dome.Empty"
  "\032\r.hx2dome.AzEl\"\000\0224\n\014dapiGotoAzEl\022\r.hx2d"
  "ome.AzEl\032\023.hx2dome.ReturnCode\"\000\0222\n\tdapiA"
  "bort\022\016.hx2dome.Empty\032\023.hx2dome.ReturnCod"
  "e\"\000\0221\n\010dapiOpen\022\016.hx2dome.Empty\032\023.hx2dom"
  "e.ReturnCode\"\000\0222\n\tdapiClose\022\016.hx2dome.Em"
  "pty\032\023.hx2dome.ReturnCode\"\000\0221\n\010dapiPark\022\016"
  ".hx2dome.Empty\032\023.hx2dome.ReturnCode\"\000\0223\n"
  "\ndapiUnpark\022\016.hx2dome.Empty\032\023.hx2dome.Re"
  "turnCode\"\000\0225\n\014dapiFindHome\022\016.hx2dome.Emp"
  "ty\032\023.hx2dome.ReturnCode\"\000\022;\n\022dapiIsGotoC"
  "omplete\022\016.hx2dome.Empty\032\023.hx2dome.IsComp"
  "lete\"\000\022;\n\022dapiIsOpenComplete\022\016.hx2dome.E"
  "mpty\032\023.hx2dome.IsComplete\"\000\022<\n\023dapiIsClo"
  "seComplete\022\016.hx2dome.Empty\032\023.hx2dome.IsC"
  "omplete\"\000\022;\n\022dapiIsParkComplete\022\016.hx2dom"
  "e.Empty\032\023.hx2dome.IsComplete\"\000\022=\n\024dapiIs"
  "UnparkComplete\022\016.hx2dome.Empty\032\023.hx2dome"
  ".IsComplete\"\000\022\?\n\026dapiIsFindHomeComplete\022"
  "\016.hx2dome.Empty\032\023.hx2dome.IsComplete\"\000\0220"
  "\n\010dapiSync\022\r.hx2dome.AzEl\032\023.hx2dome.Retu"
  "rnCode\"\000\022=\n\023deviceInfoNameShort\022\016.hx2dom"
  "e.Empty\032\024.hx2dome.BasicString\"\000\022<\n\022devic"
  "eInfoNameLong\022\016.hx2dome.Empty\032\024.hx2dome."
  "BasicString\"\000\022G\n\035deviceInfoDetailedDescr"
  "iption\022\016.hx2dome.Empty\032\024.hx2dome.BasicSt"
  "ring\"\000\022C\n\031deviceInfoFirmwareVersion\022\016.hx"
  "2dome.Empty\032\024.hx2dome.BasicString\"\000\0229\n\017d"
  "eviceInfoModel\022\016.hx2dome.Empty\032\024.hx2dome"
  ".BasicString\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_hx2dome_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_hx2dome_2eproto = {
    false, false, 1422, descriptor_table_protodef_hx2dome_2eproto,
    "hx2dome.proto",
    &descriptor_table_hx2dome_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_hx2dome_2eproto::offsets,
    file_level_metadata_hx2dome_2eproto, file_level_enum_descriptors_hx2dome_2eproto,
    file_level_service_descriptors_hx2dome_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_hx2dome_2eproto_getter() {
  return &descriptor_table_hx2dome_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_hx2dome_2eproto(&descriptor_table_hx2dome_2eproto);
namespace hx2dome {

// ===================================================================

class ReturnCode::_Internal {
 public:
};

ReturnCode::ReturnCode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hx2dome.ReturnCode)
}
ReturnCode::ReturnCode(const ReturnCode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReturnCode* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.return_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.return_code_ = from._impl_.return_code_;
  // @@protoc_insertion_point(copy_constructor:hx2dome.ReturnCode)
}

inline void ReturnCode::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.return_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReturnCode::~ReturnCode() {
  // @@protoc_insertion_point(destructor:hx2dome.ReturnCode)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReturnCode::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
}

void ReturnCode::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReturnCode::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.ReturnCode)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.return_code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReturnCode::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.return_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hx2dome.ReturnCode.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReturnCode::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.ReturnCode)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_return_code(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hx2dome.ReturnCode.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.ReturnCode)
  return target;
}

size_t ReturnCode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.ReturnCode)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_return_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReturnCode::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReturnCode::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReturnCode::GetClassData() const { return &_class_data_; }


void ReturnCode::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReturnCode*>(&to_msg);
  auto& from = static_cast<const ReturnCode&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.ReturnCode)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_return_code() != 0) {
    _this->_internal_set_return_code(from._internal_return_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReturnCode::CopyFrom(const ReturnCode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.ReturnCode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReturnCode::IsInitialized() const {
  return true;
}

void ReturnCode::InternalSwap(ReturnCode* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  swap(_impl_.return_code_, other->_impl_.return_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReturnCode::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hx2dome_2eproto_getter, &descriptor_table_hx2dome_2eproto_once,
      file_level_metadata_hx2dome_2eproto[0]);
}

// ===================================================================

class AzEl::_Internal {
 public:
};

AzEl::AzEl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hx2dome.AzEl)
}
AzEl::AzEl(const AzEl& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AzEl* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.az_){}
    , decltype(_impl_.el_){}
    , decltype(_impl_.return_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.az_, &from._impl_.az_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.return_code_) -
    reinterpret_cast<char*>(&_impl_.az_)) + sizeof(_impl_.return_code_));
  // @@protoc_insertion_point(copy_constructor:hx2dome.AzEl)
}

inline void AzEl::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.az_){0}
    , decltype(_impl_.el_){0}
    , decltype(_impl_.return_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AzEl::~AzEl() {
  // @@protoc_insertion_point(destructor:hx2dome.AzEl)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AzEl::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void AzEl::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AzEl::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.AzEl)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.az_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.return_code_) -
      reinterpret_cast<char*>(&_impl_.az_)) + sizeof(_impl_.return_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AzEl::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.return_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double az = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.az_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double el = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.el_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AzEl::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.AzEl)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_return_code(), target);
  }

  // double az = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_az = this->_internal_az();
  uint64_t raw_az;
  memcpy(&raw_az, &tmp_az, sizeof(tmp_az));
  if (raw_az != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_az(), target);
  }

  // double el = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_el = this->_internal_el();
  uint64_t raw_el;
  memcpy(&raw_el, &tmp_el, sizeof(tmp_el));
  if (raw_el != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_el(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.AzEl)
  return target;
}

size_t AzEl::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.AzEl)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double az = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_az = this->_internal_az();
  uint64_t raw_az;
  memcpy(&raw_az, &tmp_az, sizeof(tmp_az));
  if (raw_az != 0) {
    total_size += 1 + 8;
  }

  // double el = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_el = this->_internal_el();
  uint64_t raw_el;
  memcpy(&raw_el, &tmp_el, sizeof(tmp_el));
  if (raw_el != 0) {
    total_size += 1 + 8;
  }

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_return_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AzEl::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AzEl::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AzEl::GetClassData() const { return &_class_data_; }


void AzEl::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AzEl*>(&to_msg);
  auto& from = static_cast<const AzEl&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.AzEl)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_az = from._internal_az();
  uint64_t raw_az;
  memcpy(&raw_az, &tmp_az, sizeof(tmp_az));
  if (raw_az != 0) {
    _this->_internal_set_az(from._internal_az());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_el = from._internal_el();
  uint64_t raw_el;
  memcpy(&raw_el, &tmp_el, sizeof(tmp_el));
  if (raw_el != 0) {
    _this->_internal_set_el(from._internal_el());
  }
  if (from._internal_return_code() != 0) {
    _this->_internal_set_return_code(from._internal_return_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AzEl::CopyFrom(const AzEl& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.AzEl)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AzEl::IsInitialized() const {
  return true;
}

void AzEl::InternalSwap(AzEl* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AzEl, _impl_.return_code_)
      + sizeof(AzEl::_impl_.return_code_)
      - PROTOBUF_FIELD_OFFSET(AzEl, _impl_.az_)>(
          reinterpret_cast<char*>(&_impl_.az_),
          reinterpret_cast<char*>(&other->_impl_.az_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AzEl::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hx2dome_2eproto_getter, &descriptor_table_hx2dome_2eproto_once,
      file_level_metadata_hx2dome_2eproto[1]);
}

// ===================================================================

class IsComplete::_Internal {
 public:
};

IsComplete::IsComplete(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hx2dome.IsComplete)
}
IsComplete::IsComplete(const IsComplete& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IsComplete* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.return_code_){}
    , decltype(_impl_.is_complete_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.return_code_, &from._impl_.return_code_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_complete_) -
    reinterpret_cast<char*>(&_impl_.return_code_)) + sizeof(_impl_.is_complete_));
  // @@protoc_insertion_point(copy_constructor:hx2dome.IsComplete)
}

inline void IsComplete::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.return_code_){0}
    , decltype(_impl_.is_complete_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IsComplete::~IsComplete() {
  // @@protoc_insertion_point(destructor:hx2dome.IsComplete)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IsComplete::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IsComplete::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IsComplete::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.IsComplete)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.return_code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_complete_) -
      reinterpret_cast<char*>(&_impl_.return_code_)) + sizeof(_impl_.is_complete_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IsComplete::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 return_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.return_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_complete = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.is_complete_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IsComplete::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.IsComplete)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_return_code(), target);
  }

  // bool is_complete = 2;
  if (this->_internal_is_complete() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_is_complete(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.IsComplete)
  return target;
}

size_t IsComplete::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.IsComplete)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 return_code = 1;
  if (this->_internal_return_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_return_code());
  }

  // bool is_complete = 2;
  if (this->_internal_is_complete() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IsComplete::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IsComplete::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IsComplete::GetClassData() const { return &_class_data_; }


void IsComplete::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IsComplete*>(&to_msg);
  auto& from = static_cast<const IsComplete&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.IsComplete)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_return_code() != 0) {
    _this->_internal_set_return_code(from._internal_return_code());
  }
  if (from._internal_is_complete() != 0) {
    _this->_internal_set_is_complete(from._internal_is_complete());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IsComplete::CopyFrom(const IsComplete& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.IsComplete)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IsComplete::IsInitialized() const {
  return true;
}

void IsComplete::InternalSwap(IsComplete* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IsComplete, _impl_.is_complete_)
      + sizeof(IsComplete::_impl_.is_complete_)
      - PROTOBUF_FIELD_OFFSET(IsComplete, _impl_.return_code_)>(
          reinterpret_cast<char*>(&_impl_.return_code_),
          reinterpret_cast<char*>(&other->_impl_.return_code_));
}

::PROTOBUF_NAMESPACE_ID::Metadata IsComplete::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hx2dome_2eproto_getter, &descriptor_table_hx2dome_2eproto_once,
      file_level_metadata_hx2dome_2eproto[2]);
}

// ===================================================================

class BasicString::_Internal {
 public:
};

BasicString::BasicString(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:hx2dome.BasicString)
}
BasicString::BasicString(const BasicString& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BasicString* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.basic_string_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.basic_string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.basic_string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_basic_string().empty()) {
    _this->_impl_.basic_string_.Set(from._internal_basic_string(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:hx2dome.BasicString)
}

inline void BasicString::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.basic_string_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.basic_string_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.basic_string_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BasicString::~BasicString() {
  // @@protoc_insertion_point(destructor:hx2dome.BasicString)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BasicString::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.basic_string_.Destroy();
}

void BasicString::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BasicString::Clear() {
// @@protoc_insertion_point(message_clear_start:hx2dome.BasicString)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.basic_string_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BasicString::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string basic_string = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_basic_string();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "hx2dome.BasicString.basic_string"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BasicString::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hx2dome.BasicString)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string basic_string = 1;
  if (!this->_internal_basic_string().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_basic_string().data(), static_cast<int>(this->_internal_basic_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "hx2dome.BasicString.basic_string");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_basic_string(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hx2dome.BasicString)
  return target;
}

size_t BasicString::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hx2dome.BasicString)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string basic_string = 1;
  if (!this->_internal_basic_string().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_basic_string());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BasicString::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BasicString::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BasicString::GetClassData() const { return &_class_data_; }


void BasicString::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BasicString*>(&to_msg);
  auto& from = static_cast<const BasicString&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hx2dome.BasicString)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_basic_string().empty()) {
    _this->_internal_set_basic_string(from._internal_basic_string());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BasicString::CopyFrom(const BasicString& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hx2dome.BasicString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicString::IsInitialized() const {
  return true;
}

void BasicString::InternalSwap(BasicString* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.basic_string_, lhs_arena,
      &other->_impl_.basic_string_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BasicString::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hx2dome_2eproto_getter, &descriptor_table_hx2dome_2eproto_once,
      file_level_metadata_hx2dome_2eproto[3]);
}

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:hx2dome.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hx2dome.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hx2dome_2eproto_getter, &descriptor_table_hx2dome_2eproto_once,
      file_level_metadata_hx2dome_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace hx2dome
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::hx2dome::ReturnCode*
Arena::CreateMaybeMessage< ::hx2dome::ReturnCode >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hx2dome::ReturnCode >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::AzEl*
Arena::CreateMaybeMessage< ::hx2dome::AzEl >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hx2dome::AzEl >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::IsComplete*
Arena::CreateMaybeMessage< ::hx2dome::IsComplete >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hx2dome::IsComplete >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::BasicString*
Arena::CreateMaybeMessage< ::hx2dome::BasicString >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hx2dome::BasicString >(arena);
}
template<> PROTOBUF_NOINLINE ::hx2dome::Empty*
Arena::CreateMaybeMessage< ::hx2dome::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::hx2dome::Empty >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
