// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hx2dome.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hx2dome_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hx2dome_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hx2dome_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hx2dome_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hx2dome_2eproto;
namespace hx2dome {
class AzEl;
struct AzElDefaultTypeInternal;
extern AzElDefaultTypeInternal _AzEl_default_instance_;
class BasicString;
struct BasicStringDefaultTypeInternal;
extern BasicStringDefaultTypeInternal _BasicString_default_instance_;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class IsComplete;
struct IsCompleteDefaultTypeInternal;
extern IsCompleteDefaultTypeInternal _IsComplete_default_instance_;
class ReturnCode;
struct ReturnCodeDefaultTypeInternal;
extern ReturnCodeDefaultTypeInternal _ReturnCode_default_instance_;
}  // namespace hx2dome
PROTOBUF_NAMESPACE_OPEN
template<> ::hx2dome::AzEl* Arena::CreateMaybeMessage<::hx2dome::AzEl>(Arena*);
template<> ::hx2dome::BasicString* Arena::CreateMaybeMessage<::hx2dome::BasicString>(Arena*);
template<> ::hx2dome::Empty* Arena::CreateMaybeMessage<::hx2dome::Empty>(Arena*);
template<> ::hx2dome::IsComplete* Arena::CreateMaybeMessage<::hx2dome::IsComplete>(Arena*);
template<> ::hx2dome::ReturnCode* Arena::CreateMaybeMessage<::hx2dome::ReturnCode>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hx2dome {

// ===================================================================

class ReturnCode final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hx2dome.ReturnCode) */ {
 public:
  inline ReturnCode() : ReturnCode(nullptr) {}
  ~ReturnCode() override;
  explicit PROTOBUF_CONSTEXPR ReturnCode(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReturnCode(const ReturnCode& from);
  ReturnCode(ReturnCode&& from) noexcept
    : ReturnCode() {
    *this = ::std::move(from);
  }

  inline ReturnCode& operator=(const ReturnCode& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReturnCode& operator=(ReturnCode&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReturnCode& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReturnCode* internal_default_instance() {
    return reinterpret_cast<const ReturnCode*>(
               &_ReturnCode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReturnCode& a, ReturnCode& b) {
    a.Swap(&b);
  }
  inline void Swap(ReturnCode* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReturnCode* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReturnCode* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReturnCode>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReturnCode& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReturnCode& from) {
    ReturnCode::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReturnCode* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hx2dome.ReturnCode";
  }
  protected:
  explicit ReturnCode(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMessageFieldNumber = 2,
    kReturnCodeFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int32 return_code = 1;
  void clear_return_code();
  int32_t return_code() const;
  void set_return_code(int32_t value);
  private:
  int32_t _internal_return_code() const;
  void _internal_set_return_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:hx2dome.ReturnCode)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    int32_t return_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class AzEl final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hx2dome.AzEl) */ {
 public:
  inline AzEl() : AzEl(nullptr) {}
  ~AzEl() override;
  explicit PROTOBUF_CONSTEXPR AzEl(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AzEl(const AzEl& from);
  AzEl(AzEl&& from) noexcept
    : AzEl() {
    *this = ::std::move(from);
  }

  inline AzEl& operator=(const AzEl& from) {
    CopyFrom(from);
    return *this;
  }
  inline AzEl& operator=(AzEl&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AzEl& default_instance() {
    return *internal_default_instance();
  }
  static inline const AzEl* internal_default_instance() {
    return reinterpret_cast<const AzEl*>(
               &_AzEl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AzEl& a, AzEl& b) {
    a.Swap(&b);
  }
  inline void Swap(AzEl* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AzEl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AzEl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AzEl>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AzEl& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AzEl& from) {
    AzEl::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AzEl* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hx2dome.AzEl";
  }
  protected:
  explicit AzEl(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAzFieldNumber = 2,
    kElFieldNumber = 3,
    kReturnCodeFieldNumber = 1,
  };
  // double az = 2;
  void clear_az();
  double az() const;
  void set_az(double value);
  private:
  double _internal_az() const;
  void _internal_set_az(double value);
  public:

  // double el = 3;
  void clear_el();
  double el() const;
  void set_el(double value);
  private:
  double _internal_el() const;
  void _internal_set_el(double value);
  public:

  // int32 return_code = 1;
  void clear_return_code();
  int32_t return_code() const;
  void set_return_code(int32_t value);
  private:
  int32_t _internal_return_code() const;
  void _internal_set_return_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:hx2dome.AzEl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double az_;
    double el_;
    int32_t return_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class IsComplete final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hx2dome.IsComplete) */ {
 public:
  inline IsComplete() : IsComplete(nullptr) {}
  ~IsComplete() override;
  explicit PROTOBUF_CONSTEXPR IsComplete(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IsComplete(const IsComplete& from);
  IsComplete(IsComplete&& from) noexcept
    : IsComplete() {
    *this = ::std::move(from);
  }

  inline IsComplete& operator=(const IsComplete& from) {
    CopyFrom(from);
    return *this;
  }
  inline IsComplete& operator=(IsComplete&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IsComplete& default_instance() {
    return *internal_default_instance();
  }
  static inline const IsComplete* internal_default_instance() {
    return reinterpret_cast<const IsComplete*>(
               &_IsComplete_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IsComplete& a, IsComplete& b) {
    a.Swap(&b);
  }
  inline void Swap(IsComplete* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IsComplete* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IsComplete* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IsComplete>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IsComplete& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IsComplete& from) {
    IsComplete::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IsComplete* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hx2dome.IsComplete";
  }
  protected:
  explicit IsComplete(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReturnCodeFieldNumber = 1,
    kIsCompleteFieldNumber = 2,
  };
  // int32 return_code = 1;
  void clear_return_code();
  int32_t return_code() const;
  void set_return_code(int32_t value);
  private:
  int32_t _internal_return_code() const;
  void _internal_set_return_code(int32_t value);
  public:

  // bool is_complete = 2;
  void clear_is_complete();
  bool is_complete() const;
  void set_is_complete(bool value);
  private:
  bool _internal_is_complete() const;
  void _internal_set_is_complete(bool value);
  public:

  // @@protoc_insertion_point(class_scope:hx2dome.IsComplete)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t return_code_;
    bool is_complete_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class BasicString final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hx2dome.BasicString) */ {
 public:
  inline BasicString() : BasicString(nullptr) {}
  ~BasicString() override;
  explicit PROTOBUF_CONSTEXPR BasicString(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BasicString(const BasicString& from);
  BasicString(BasicString&& from) noexcept
    : BasicString() {
    *this = ::std::move(from);
  }

  inline BasicString& operator=(const BasicString& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicString& operator=(BasicString&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BasicString& default_instance() {
    return *internal_default_instance();
  }
  static inline const BasicString* internal_default_instance() {
    return reinterpret_cast<const BasicString*>(
               &_BasicString_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BasicString& a, BasicString& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicString* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BasicString* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BasicString* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BasicString>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BasicString& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BasicString& from) {
    BasicString::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicString* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hx2dome.BasicString";
  }
  protected:
  explicit BasicString(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBasicStringFieldNumber = 1,
  };
  // string basic_string = 1;
  void clear_basic_string();
  const std::string& basic_string() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_basic_string(ArgT0&& arg0, ArgT... args);
  std::string* mutable_basic_string();
  PROTOBUF_NODISCARD std::string* release_basic_string();
  void set_allocated_basic_string(std::string* basic_string);
  private:
  const std::string& _internal_basic_string() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_basic_string(const std::string& value);
  std::string* _internal_mutable_basic_string();
  public:

  // @@protoc_insertion_point(class_scope:hx2dome.BasicString)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr basic_string_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_hx2dome_2eproto;
};
// -------------------------------------------------------------------

class Empty final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:hx2dome.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}
  explicit PROTOBUF_CONSTEXPR Empty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Empty& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hx2dome.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hx2dome.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_hx2dome_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReturnCode

// int32 return_code = 1;
inline void ReturnCode::clear_return_code() {
  _impl_.return_code_ = 0;
}
inline int32_t ReturnCode::_internal_return_code() const {
  return _impl_.return_code_;
}
inline int32_t ReturnCode::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.ReturnCode.return_code)
  return _internal_return_code();
}
inline void ReturnCode::_internal_set_return_code(int32_t value) {
  
  _impl_.return_code_ = value;
}
inline void ReturnCode::set_return_code(int32_t value) {
  _internal_set_return_code(value);
  // @@protoc_insertion_point(field_set:hx2dome.ReturnCode.return_code)
}

// string error_message = 2;
inline void ReturnCode::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& ReturnCode::error_message() const {
  // @@protoc_insertion_point(field_get:hx2dome.ReturnCode.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReturnCode::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hx2dome.ReturnCode.error_message)
}
inline std::string* ReturnCode::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:hx2dome.ReturnCode.error_message)
  return _s;
}
inline const std::string& ReturnCode::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void ReturnCode::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* ReturnCode::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* ReturnCode::release_error_message() {
  // @@protoc_insertion_point(field_release:hx2dome.ReturnCode.error_message)
  return _impl_.error_message_.Release();
}
inline void ReturnCode::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hx2dome.ReturnCode.error_message)
}

// -------------------------------------------------------------------

// AzEl

// int32 return_code = 1;
inline void AzEl::clear_return_code() {
  _impl_.return_code_ = 0;
}
inline int32_t AzEl::_internal_return_code() const {
  return _impl_.return_code_;
}
inline int32_t AzEl::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.return_code)
  return _internal_return_code();
}
inline void AzEl::_internal_set_return_code(int32_t value) {
  
  _impl_.return_code_ = value;
}
inline void AzEl::set_return_code(int32_t value) {
  _internal_set_return_code(value);
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.return_code)
}

// double az = 2;
inline void AzEl::clear_az() {
  _impl_.az_ = 0;
}
inline double AzEl::_internal_az() const {
  return _impl_.az_;
}
inline double AzEl::az() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.az)
  return _internal_az();
}
inline void AzEl::_internal_set_az(double value) {
  
  _impl_.az_ = value;
}
inline void AzEl::set_az(double value) {
  _internal_set_az(value);
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.az)
}

// double el = 3;
inline void AzEl::clear_el() {
  _impl_.el_ = 0;
}
inline double AzEl::_internal_el() const {
  return _impl_.el_;
}
inline double AzEl::el() const {
  // @@protoc_insertion_point(field_get:hx2dome.AzEl.el)
  return _internal_el();
}
inline void AzEl::_internal_set_el(double value) {
  
  _impl_.el_ = value;
}
inline void AzEl::set_el(double value) {
  _internal_set_el(value);
  // @@protoc_insertion_point(field_set:hx2dome.AzEl.el)
}

// -------------------------------------------------------------------

// IsComplete

// int32 return_code = 1;
inline void IsComplete::clear_return_code() {
  _impl_.return_code_ = 0;
}
inline int32_t IsComplete::_internal_return_code() const {
  return _impl_.return_code_;
}
inline int32_t IsComplete::return_code() const {
  // @@protoc_insertion_point(field_get:hx2dome.IsComplete.return_code)
  return _internal_return_code();
}
inline void IsComplete::_internal_set_return_code(int32_t value) {
  
  _impl_.return_code_ = value;
}
inline void IsComplete::set_return_code(int32_t value) {
  _internal_set_return_code(value);
  // @@protoc_insertion_point(field_set:hx2dome.IsComplete.return_code)
}

// bool is_complete = 2;
inline void IsComplete::clear_is_complete() {
  _impl_.is_complete_ = false;
}
inline bool IsComplete::_internal_is_complete() const {
  return _impl_.is_complete_;
}
inline bool IsComplete::is_complete() const {
  // @@protoc_insertion_point(field_get:hx2dome.IsComplete.is_complete)
  return _internal_is_complete();
}
inline void IsComplete::_internal_set_is_complete(bool value) {
  
  _impl_.is_complete_ = value;
}
inline void IsComplete::set_is_complete(bool value) {
  _internal_set_is_complete(value);
  // @@protoc_insertion_point(field_set:hx2dome.IsComplete.is_complete)
}

// -------------------------------------------------------------------

// BasicString

// string basic_string = 1;
inline void BasicString::clear_basic_string() {
  _impl_.basic_string_.ClearToEmpty();
}
inline const std::string& BasicString::basic_string() const {
  // @@protoc_insertion_point(field_get:hx2dome.BasicString.basic_string)
  return _internal_basic_string();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BasicString::set_basic_string(ArgT0&& arg0, ArgT... args) {
 
 _impl_.basic_string_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:hx2dome.BasicString.basic_string)
}
inline std::string* BasicString::mutable_basic_string() {
  std::string* _s = _internal_mutable_basic_string();
  // @@protoc_insertion_point(field_mutable:hx2dome.BasicString.basic_string)
  return _s;
}
inline const std::string& BasicString::_internal_basic_string() const {
  return _impl_.basic_string_.Get();
}
inline void BasicString::_internal_set_basic_string(const std::string& value) {
  
  _impl_.basic_string_.Set(value, GetArenaForAllocation());
}
inline std::string* BasicString::_internal_mutable_basic_string() {
  
  return _impl_.basic_string_.Mutable(GetArenaForAllocation());
}
inline std::string* BasicString::release_basic_string() {
  // @@protoc_insertion_point(field_release:hx2dome.BasicString.basic_string)
  return _impl_.basic_string_.Release();
}
inline void BasicString::set_allocated_basic_string(std::string* basic_string) {
  if (basic_string != nullptr) {
    
  } else {
    
  }
  _impl_.basic_string_.SetAllocated(basic_string, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.basic_string_.IsDefault()) {
    _impl_.basic_string_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:hx2dome.BasicString.basic_string)
}

// -------------------------------------------------------------------

// Empty

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hx2dome

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hx2dome_2eproto
