---
name: Huntsman Dome Controller
######################
# LOGGING PARAMETERS #
######################
# critical – for errors that lead to termination
# error – for errors that occur, but are handled
# warning – for exceptional circumstances that might not be errors
# notice – for non-error messages you usually want to see
# info – for messages you usually don’t want to see
# debug – for debug messages
logo: True
log_file_level: 'DEBUG'
log_stderr_level: 'NOTICE'
server_log_file_level: 'DEBUG'
server_log_stderr_level: 'WARNING'
###################
# DOME PARAMETERS #
###################
home_azimuth: 31.5
az_position_tolerance: 1.7
park_azimuth: 300
degrees_per_tick: 1.075
encoder_pin_number: 26
home_sensor_pin_number: 20
rotation_relay_pin_number: 13
direction_relay_pin_number: 19
bounce_time: 0.001
num_cal_rotations: 2
led_brightness: 0x01
