---
name: Huntsman Dome Controller
home_azimuth: 0
testing: False
debug_lights: True
az_position_tolerance: 1.0
degrees_per_tick: 1.16
encoder_pin_number: 26
home_sensor_pin_number: 20
rotation_relay_pin_number: 13
direction_relay_pin_number: 19
bounce_time: 0.001
num_cal_rotations: 2
