---
name: Huntsman Dome Controller
log_file_level: 'DEBUG'
log_stderr_level: 'NOTICE'
home_azimuth: 31.5
az_position_tolerance: 1.7
degrees_per_tick: 1.075
encoder_pin_number: 26
home_sensor_pin_number: 20
rotation_relay_pin_number: 13
direction_relay_pin_number: 19
bounce_time: 0.001
num_cal_rotations: 2
led_brightness: 0x01
