# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hx2dome_pb2 as hx2dome__pb2


class HX2DomeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.dapiGetAzEl = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiGetAzEl',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.AzEl.FromString,
        )
    self.dapiGotoAzEl = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiGotoAzEl',
        request_serializer=hx2dome__pb2.AzEl.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiAbort = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiAbort',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiOpen = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiOpen',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiClose = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiClose',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiPark = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiPark',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiUnpark = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiUnpark',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiFindHome = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiFindHome',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.dapiIsGotoComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsGotoComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiIsOpenComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsOpenComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiIsCloseComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsCloseComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiIsParkComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsParkComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiIsUnparkComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsUnparkComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiIsFindHomeComplete = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiIsFindHomeComplete',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.IsComplete.FromString,
        )
    self.dapiSync = channel.unary_unary(
        '/hx2dome.HX2Dome/dapiSync',
        request_serializer=hx2dome__pb2.AzEl.SerializeToString,
        response_deserializer=hx2dome__pb2.ReturnCode.FromString,
        )
    self.deviceInfoNameShort = channel.unary_unary(
        '/hx2dome.HX2Dome/deviceInfoNameShort',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.BasicString.FromString,
        )
    self.deviceInfoNameLong = channel.unary_unary(
        '/hx2dome.HX2Dome/deviceInfoNameLong',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.BasicString.FromString,
        )
    self.deviceInfoDetailedDescription = channel.unary_unary(
        '/hx2dome.HX2Dome/deviceInfoDetailedDescription',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.BasicString.FromString,
        )
    self.deviceInfoFirmwareVersion = channel.unary_unary(
        '/hx2dome.HX2Dome/deviceInfoFirmwareVersion',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.BasicString.FromString,
        )
    self.deviceInfoModel = channel.unary_unary(
        '/hx2dome.HX2Dome/deviceInfoModel',
        request_serializer=hx2dome__pb2.Empty.SerializeToString,
        response_deserializer=hx2dome__pb2.BasicString.FromString,
        )


class HX2DomeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def dapiGetAzEl(self, request, context):
    """Dome API
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiGotoAzEl(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiAbort(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiOpen(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiClose(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiPark(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiUnpark(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiFindHome(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsGotoComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsOpenComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsCloseComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsParkComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsUnparkComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiIsFindHomeComplete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def dapiSync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deviceInfoNameShort(self, request, context):
    """Hardware Info Interface
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deviceInfoNameLong(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deviceInfoDetailedDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deviceInfoFirmwareVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deviceInfoModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HX2DomeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'dapiGetAzEl': grpc.unary_unary_rpc_method_handler(
          servicer.dapiGetAzEl,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.AzEl.SerializeToString,
      ),
      'dapiGotoAzEl': grpc.unary_unary_rpc_method_handler(
          servicer.dapiGotoAzEl,
          request_deserializer=hx2dome__pb2.AzEl.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiAbort': grpc.unary_unary_rpc_method_handler(
          servicer.dapiAbort,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiOpen': grpc.unary_unary_rpc_method_handler(
          servicer.dapiOpen,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiClose': grpc.unary_unary_rpc_method_handler(
          servicer.dapiClose,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiPark': grpc.unary_unary_rpc_method_handler(
          servicer.dapiPark,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiUnpark': grpc.unary_unary_rpc_method_handler(
          servicer.dapiUnpark,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiFindHome': grpc.unary_unary_rpc_method_handler(
          servicer.dapiFindHome,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'dapiIsGotoComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsGotoComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiIsOpenComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsOpenComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiIsCloseComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsCloseComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiIsParkComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsParkComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiIsUnparkComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsUnparkComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiIsFindHomeComplete': grpc.unary_unary_rpc_method_handler(
          servicer.dapiIsFindHomeComplete,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
      ),
      'dapiSync': grpc.unary_unary_rpc_method_handler(
          servicer.dapiSync,
          request_deserializer=hx2dome__pb2.AzEl.FromString,
          response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
      ),
      'deviceInfoNameShort': grpc.unary_unary_rpc_method_handler(
          servicer.deviceInfoNameShort,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.BasicString.SerializeToString,
      ),
      'deviceInfoNameLong': grpc.unary_unary_rpc_method_handler(
          servicer.deviceInfoNameLong,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.BasicString.SerializeToString,
      ),
      'deviceInfoDetailedDescription': grpc.unary_unary_rpc_method_handler(
          servicer.deviceInfoDetailedDescription,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.BasicString.SerializeToString,
      ),
      'deviceInfoFirmwareVersion': grpc.unary_unary_rpc_method_handler(
          servicer.deviceInfoFirmwareVersion,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.BasicString.SerializeToString,
      ),
      'deviceInfoModel': grpc.unary_unary_rpc_method_handler(
          servicer.deviceInfoModel,
          request_deserializer=hx2dome__pb2.Empty.FromString,
          response_serializer=hx2dome__pb2.BasicString.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hx2dome.HX2Dome', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
