# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hx2dome_pb2 as hx2dome__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hx2dome_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HX2DomeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.dapiGetAzEl = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiGetAzEl',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.AzEl.FromString,
                _registered_method=True)
        self.dapiGotoAzEl = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiGotoAzEl',
                request_serializer=hx2dome__pb2.AzEl.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiAbort = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiAbort',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiOpen = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiOpen',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiClose = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiClose',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiPark = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiPark',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiUnpark = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiUnpark',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiFindHome = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiFindHome',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.dapiIsGotoComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsGotoComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiIsOpenComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsOpenComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiIsCloseComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsCloseComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiIsParkComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsParkComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiIsUnparkComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsUnparkComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiIsFindHomeComplete = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiIsFindHomeComplete',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.IsComplete.FromString,
                _registered_method=True)
        self.dapiSync = channel.unary_unary(
                '/hx2dome.HX2Dome/dapiSync',
                request_serializer=hx2dome__pb2.AzEl.SerializeToString,
                response_deserializer=hx2dome__pb2.ReturnCode.FromString,
                _registered_method=True)
        self.deviceInfoNameShort = channel.unary_unary(
                '/hx2dome.HX2Dome/deviceInfoNameShort',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.BasicString.FromString,
                _registered_method=True)
        self.deviceInfoNameLong = channel.unary_unary(
                '/hx2dome.HX2Dome/deviceInfoNameLong',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.BasicString.FromString,
                _registered_method=True)
        self.deviceInfoDetailedDescription = channel.unary_unary(
                '/hx2dome.HX2Dome/deviceInfoDetailedDescription',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.BasicString.FromString,
                _registered_method=True)
        self.deviceInfoFirmwareVersion = channel.unary_unary(
                '/hx2dome.HX2Dome/deviceInfoFirmwareVersion',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.BasicString.FromString,
                _registered_method=True)
        self.deviceInfoModel = channel.unary_unary(
                '/hx2dome.HX2Dome/deviceInfoModel',
                request_serializer=hx2dome__pb2.Empty.SerializeToString,
                response_deserializer=hx2dome__pb2.BasicString.FromString,
                _registered_method=True)


class HX2DomeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def dapiGetAzEl(self, request, context):
        """Dome API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiGotoAzEl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiOpen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiPark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiUnpark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiFindHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsGotoComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsOpenComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsCloseComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsParkComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsUnparkComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiIsFindHomeComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dapiSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deviceInfoNameShort(self, request, context):
        """Hardware Info Interface
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deviceInfoNameLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deviceInfoDetailedDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deviceInfoFirmwareVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deviceInfoModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HX2DomeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'dapiGetAzEl': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiGetAzEl,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.AzEl.SerializeToString,
            ),
            'dapiGotoAzEl': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiGotoAzEl,
                    request_deserializer=hx2dome__pb2.AzEl.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiAbort,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiOpen': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiOpen,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiClose': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiClose,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiPark': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiPark,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiUnpark': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiUnpark,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiFindHome': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiFindHome,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'dapiIsGotoComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsGotoComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiIsOpenComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsOpenComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiIsCloseComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsCloseComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiIsParkComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsParkComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiIsUnparkComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsUnparkComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiIsFindHomeComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiIsFindHomeComplete,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.IsComplete.SerializeToString,
            ),
            'dapiSync': grpc.unary_unary_rpc_method_handler(
                    servicer.dapiSync,
                    request_deserializer=hx2dome__pb2.AzEl.FromString,
                    response_serializer=hx2dome__pb2.ReturnCode.SerializeToString,
            ),
            'deviceInfoNameShort': grpc.unary_unary_rpc_method_handler(
                    servicer.deviceInfoNameShort,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.BasicString.SerializeToString,
            ),
            'deviceInfoNameLong': grpc.unary_unary_rpc_method_handler(
                    servicer.deviceInfoNameLong,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.BasicString.SerializeToString,
            ),
            'deviceInfoDetailedDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.deviceInfoDetailedDescription,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.BasicString.SerializeToString,
            ),
            'deviceInfoFirmwareVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.deviceInfoFirmwareVersion,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.BasicString.SerializeToString,
            ),
            'deviceInfoModel': grpc.unary_unary_rpc_method_handler(
                    servicer.deviceInfoModel,
                    request_deserializer=hx2dome__pb2.Empty.FromString,
                    response_serializer=hx2dome__pb2.BasicString.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hx2dome.HX2Dome', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hx2dome.HX2Dome', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HX2Dome(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def dapiGetAzEl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiGetAzEl',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.AzEl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiGotoAzEl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiGotoAzEl',
            hx2dome__pb2.AzEl.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiAbort',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiOpen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiOpen',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiClose',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiPark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiPark',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiUnpark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiUnpark',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiFindHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiFindHome',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsGotoComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsGotoComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsOpenComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsOpenComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsCloseComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsCloseComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsParkComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsParkComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsUnparkComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsUnparkComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiIsFindHomeComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiIsFindHomeComplete',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.IsComplete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dapiSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/dapiSync',
            hx2dome__pb2.AzEl.SerializeToString,
            hx2dome__pb2.ReturnCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deviceInfoNameShort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/deviceInfoNameShort',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.BasicString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deviceInfoNameLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/deviceInfoNameLong',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.BasicString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deviceInfoDetailedDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/deviceInfoDetailedDescription',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.BasicString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deviceInfoFirmwareVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/deviceInfoFirmwareVersion',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.BasicString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deviceInfoModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hx2dome.HX2Dome/deviceInfoModel',
            hx2dome__pb2.Empty.SerializeToString,
            hx2dome__pb2.BasicString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
